### ISSUE TITLE
Support for re-indexing?

### ISSUE THREAD

**Issue by abingham** [youngker/helm-codesearch.el#1]
Does this package have support for re-indexing the existing projects? If I run `cindex` with no arguments on the command line, it will update the index with any changes that have occurred. I don't see how to do that with helm-codesearch, but it would be nice to have.

**Comment by youngker** [comment]
Hi abingham
Yes, you can re-indexing with run again helm-codesearch-create-csearchindex function in the existing projects.

Thank you.

**Comment by abingham** [comment]
Ah, I see now. It looks like helm-codesearch tries to have separate index files for each project, i.e. each time you run `helm-codesearch-create-csearchindex` you get a new index file in that directory. This is a bit different from how many people use codesearch, I think. They want to put multiple projects (e.g. a large corporate codebase) into a single index that they can search at once. Two important benefits of this approach are a) users can search all of their projects quickly and b) they can update them all with a single command.

Do you plan to support putting multiple projects in a single file? I really like the helm interface you're using, but I'm not sure I can live with single-project indexes. The package I wrote, [codesearch.el](https://github.com/abingham/codesearch.el), lets the user specify a single index file, and it then uses that index file for all of its work. I think this is a bit closer to how most people use codesearch, to be honest.

**Comment by youngker** [comment]
Good point!!! :+1: 
I'll add support for multiple projects.

**Comment by abingham** [comment]
Would you consider combining our two projects? It seems wrong to have two implementations of methods to use codesearch. We could settle on a single body of code for executing the codesearch tools, managing the index file, and so forth. Then we could have add-ons for doing the display; your helm code and my much more basic display code would be two examples.

I think we could ultimately structure things so that all users get the benefit of a single, solid core implementation, but they could still use it without needing to have helm as well.

**Comment by youngker** [comment]
now, helm-codesearch support the multiple projects.

**Comment by abingham** [comment]
This seems to work pretty well now. Thanks!
