### ISSUE TITLE
feature request: helm-able search history

### ISSUE THREAD

**Issue by dbldippy** [youngker/helm-codesearch.el#10]
I use helm-codesearch a lot and have to re-enter previous searches often. I can use M-p and M-n to cycle through past searches, however it would be more convenient to be able to search the search history with helm.

**Comment by youngker** [comment]
Hi myk3v
Nice comments, I will consider that.

**Comment by youngker** [comment]
Please check this commit 1dd925cdc7527f4e1cfb433d823d1be805455df3

Thanks you

**Comment by youngker** [comment]
Fixed an issue that sometimes lost keymap.
