### ISSUE TITLE
Updating readme?

### ISSUE THREAD

**Issue by JinsukKim** [youngker/helm-codesearch.el#7]
helm-codesearch became indispensable for my emacs dev environment. Thanks for the ongoing effort to make it better.

- Version 0.5.0 documents 3 key-bindings but only `helm-codesearch-run-ignore-case` is available. 
- I kind of miss an old way (if this is a deliberate change) of finding patterns with `-f` option to narrow down the files to search. I wonder if this can be put back. Looks like it stopped working from `b6d3480`

Cheers,

**Comment by JinsukKim** [comment]
Sorry a wrong bisect - I think it was `fcc62fa57`

**Comment by youngker** [comment]
Dear Jinsuk

- I fixed "helm-codesearch-run-set-filename" issue from 39a5e30613159dfec22b3727b1610a230ac9f5b1
Now in the melpa version, 3 key-bindings working well. please let me know more detail, if you have some problem.
- Yes I agree with you, I will consider revert to command line option

Thank you,
YoungJoo Lee

**Comment by JinsukKim** [comment]
Thank you very much for the update. Closing.
